version: '3.7'

services:

  chrome_standalone:
    image: selenium/standalone-chrome-debug:3.141.59-yttrium
    ports:
      - "5900:5900"
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    shm_size: '2g'

  rf_runner:
    image: macejiko/robotdocker:3.7-alpine
    volumes:
      - .:/user/local
    environment:
      - ENV_URL=${ENV_URL}
      - SELENIUM_GRID_HUB=chrome_standalone
    command: >
      sh -c "
      sleep 10;

      robot
      ${OPTIONS}
      -d report
      -b debug.robot
      -e not_ready
      -n bug
      --nostatusrc
      test_suites/${TEST_CASE}"


